var gtitle = d3.select('.dchart').append("g")
 gtitle.append('foreignObject')
 .call(d3.drag().on("start", dragstarted).on("drag", dragged))
 .attr('id','gtitle')
 .attr('x', width - 200)
 .attr('y', 15)
 .attr("width", "141px")
 .attr("height", "37px")
 .append('xhtml:div')
 .attr('id','dgtitle')
 .attr("contentEditable", true)
 .style("cursor", "move")
 .html("<a style='color:darkblue'>♦</a> Raw Plot")
 .style('font-size','30px')
 .style('width','fit-content')
 .on("contextmenu", function(data,index){d3.event.preventDefault()});
