svg.append("g")
 .attr("class", "y axis")
 .call(d3.axisLeft(yScale).ticks(7))
 .attr("transform", "translate(50, 0)")
 .attr('font-size','25px');
 
 d3.select('.dchart')
 .append('foreignObject')
 .call(d3.drag().on("start", dragstarted).on("drag", dragged))
 .attr('class','tyaxis')
 .attr('x', - width*0.04)
 .attr('y', height*0.35)
 .attr("width", "20%")
 .attr("height", "100%")
 .append('xhtml:div')
 .attr('id','dtyaxis')
 .style("cursor", "move")
 .attr("contentEditable", true)
 .html('Intensity (a.u.)')
 .style('font-size','30px')
 .style("transform", "rotate(-90deg) translateX(-100%) translateY(40%)")
 .style('transform-origin','left')
 .style('width','fit-content')
 .on("contextmenu", function(data,index){d3.event.preventDefault()});
